
    create table contact_messages (
        is_important boolean not null,
        is_read boolean not null,
        id bigint generated by default as identity,
        read_at timestamp(6),
        sent_at timestamp(6) not null,
        message varchar(2000) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        subject varchar(255) not null,
        primary key (id)
    );

    create table events (
        capacite_max integer not null check (capacite_max>=1),
        prix_unitaire float(53) not null check (prix_unitaire>=0),
        date_creation timestamp(6) not null,
        date_debut timestamp(6) not null,
        date_fin timestamp(6),
        date_modification timestamp(6),
        id bigint generated by default as identity,
        organisateur_id bigint not null,
        titre varchar(100) not null,
        image_path varchar(500),
        description varchar(1000),
        lieu varchar(255) not null,
        ville varchar(255) not null,
        categorie enum ('AUTRE','CONCERT','CONFERENCE','SPORT','THEATRE') not null,
        statut enum ('ANNULE','BROUILLON','PUBLIE','TERMINE') not null,
        primary key (id)
    );

    create table reservations (
        montant_total float(53) not null,
        nombre_places integer not null,
        date_reservation timestamp(6) not null,
        evenement_id bigint not null,
        id bigint generated by default as identity,
        utilisateur_id bigint not null,
        commentaire varchar(500),
        code_reservation varchar(255) not null unique,
        statut enum ('ANNULEE','CONFIRMEE','EN_ATTENTE') not null,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role enum ('ADMIN','CLIENT','ORGANIZER') not null,
        primary key (id)
    );

    alter table if exists events 
       add constraint FK5yk99wir13s55ueack8plvtyd 
       foreign key (organisateur_id) 
       references users;

    alter table if exists reservations 
       add constraint FK8jesmpbtkragkbvbrfleldwhr 
       foreign key (evenement_id) 
       references events;

    alter table if exists reservations 
       add constraint FKog5mieccgchsbj6f97w02uj53 
       foreign key (utilisateur_id) 
       references users;

    create table contact_messages (
        is_important boolean not null,
        is_read boolean not null,
        id bigint generated by default as identity,
        read_at timestamp(6),
        sent_at timestamp(6) not null,
        message varchar(2000) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        subject varchar(255) not null,
        primary key (id)
    );

    create table events (
        capacite_max integer not null check (capacite_max>=1),
        prix_unitaire float(53) not null check (prix_unitaire>=0),
        date_creation timestamp(6) not null,
        date_debut timestamp(6) not null,
        date_fin timestamp(6),
        date_modification timestamp(6),
        id bigint generated by default as identity,
        organisateur_id bigint not null,
        titre varchar(100) not null,
        image_path varchar(500),
        description varchar(1000),
        lieu varchar(255) not null,
        ville varchar(255) not null,
        categorie enum ('AUTRE','CONCERT','CONFERENCE','SPORT','THEATRE') not null,
        statut enum ('ANNULE','BROUILLON','PUBLIE','TERMINE') not null,
        primary key (id)
    );

    create table reservations (
        montant_total float(53) not null,
        nombre_places integer not null,
        date_reservation timestamp(6) not null,
        evenement_id bigint not null,
        id bigint generated by default as identity,
        utilisateur_id bigint not null,
        commentaire varchar(500),
        code_reservation varchar(255) not null unique,
        statut enum ('ANNULEE','CONFIRMEE','EN_ATTENTE') not null,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role enum ('ADMIN','CLIENT','ORGANIZER') not null,
        primary key (id)
    );

    alter table if exists events 
       add constraint FK5yk99wir13s55ueack8plvtyd 
       foreign key (organisateur_id) 
       references users;

    alter table if exists reservations 
       add constraint FK8jesmpbtkragkbvbrfleldwhr 
       foreign key (evenement_id) 
       references events;

    alter table if exists reservations 
       add constraint FKog5mieccgchsbj6f97w02uj53 
       foreign key (utilisateur_id) 
       references users;

    create table contact_messages (
        is_important boolean not null,
        is_read boolean not null,
        id bigint generated by default as identity,
        read_at timestamp(6),
        sent_at timestamp(6) not null,
        message varchar(2000) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        subject varchar(255) not null,
        primary key (id)
    );

    create table events (
        capacite_max integer not null check (capacite_max>=1),
        prix_unitaire float(53) not null check (prix_unitaire>=0),
        date_creation timestamp(6) not null,
        date_debut timestamp(6) not null,
        date_fin timestamp(6),
        date_modification timestamp(6),
        id bigint generated by default as identity,
        organisateur_id bigint not null,
        titre varchar(100) not null,
        image_path varchar(500),
        description varchar(1000),
        lieu varchar(255) not null,
        ville varchar(255) not null,
        categorie enum ('AUTRE','CONCERT','CONFERENCE','SPORT','THEATRE') not null,
        statut enum ('ANNULE','BROUILLON','PUBLIE','TERMINE') not null,
        primary key (id)
    );

    create table reservations (
        montant_total float(53) not null,
        nombre_places integer not null,
        date_reservation timestamp(6) not null,
        evenement_id bigint not null,
        id bigint generated by default as identity,
        utilisateur_id bigint not null,
        commentaire varchar(500),
        code_reservation varchar(255) not null unique,
        statut enum ('ANNULEE','CONFIRMEE','EN_ATTENTE') not null,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role enum ('ADMIN','CLIENT','ORGANIZER') not null,
        primary key (id)
    );

    alter table if exists events 
       add constraint FK5yk99wir13s55ueack8plvtyd 
       foreign key (organisateur_id) 
       references users;

    alter table if exists reservations 
       add constraint FK8jesmpbtkragkbvbrfleldwhr 
       foreign key (evenement_id) 
       references events;

    alter table if exists reservations 
       add constraint FKog5mieccgchsbj6f97w02uj53 
       foreign key (utilisateur_id) 
       references users;

    create table contact_messages (
        is_important boolean not null,
        is_read boolean not null,
        id bigint generated by default as identity,
        read_at timestamp(6),
        sent_at timestamp(6) not null,
        message varchar(2000) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        subject varchar(255) not null,
        primary key (id)
    );

    create table events (
        capacite_max integer not null check (capacite_max>=1),
        prix_unitaire float(53) not null check (prix_unitaire>=0),
        date_creation timestamp(6) not null,
        date_debut timestamp(6) not null,
        date_fin timestamp(6),
        date_modification timestamp(6),
        id bigint generated by default as identity,
        organisateur_id bigint not null,
        titre varchar(100) not null,
        image_path varchar(500),
        description varchar(1000),
        lieu varchar(255) not null,
        ville varchar(255) not null,
        categorie enum ('AUTRE','CONCERT','CONFERENCE','SPORT','THEATRE') not null,
        statut enum ('ANNULE','BROUILLON','PUBLIE','TERMINE') not null,
        primary key (id)
    );

    create table reservations (
        montant_total float(53) not null,
        nombre_places integer not null,
        date_reservation timestamp(6) not null,
        evenement_id bigint not null,
        id bigint generated by default as identity,
        utilisateur_id bigint not null,
        commentaire varchar(500),
        code_reservation varchar(255) not null unique,
        statut enum ('ANNULEE','CONFIRMEE','EN_ATTENTE') not null,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role enum ('ADMIN','CLIENT','ORGANIZER') not null,
        primary key (id)
    );

    alter table if exists events 
       add constraint FK5yk99wir13s55ueack8plvtyd 
       foreign key (organisateur_id) 
       references users;

    alter table if exists reservations 
       add constraint FK8jesmpbtkragkbvbrfleldwhr 
       foreign key (evenement_id) 
       references events;

    alter table if exists reservations 
       add constraint FKog5mieccgchsbj6f97w02uj53 
       foreign key (utilisateur_id) 
       references users;

    create table contact_messages (
        is_important boolean not null,
        is_read boolean not null,
        id bigint generated by default as identity,
        read_at timestamp(6),
        sent_at timestamp(6) not null,
        message varchar(2000) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        subject varchar(255) not null,
        primary key (id)
    );

    create table events (
        capacite_max integer not null check (capacite_max>=1),
        prix_unitaire float(53) not null check (prix_unitaire>=0),
        date_creation timestamp(6) not null,
        date_debut timestamp(6) not null,
        date_fin timestamp(6),
        date_modification timestamp(6),
        id bigint generated by default as identity,
        organisateur_id bigint not null,
        titre varchar(100) not null,
        image_path varchar(500),
        description varchar(1000),
        lieu varchar(255) not null,
        ville varchar(255) not null,
        categorie enum ('AUTRE','CONCERT','CONFERENCE','SPORT','THEATRE') not null,
        statut enum ('ANNULE','BROUILLON','PUBLIE','TERMINE') not null,
        primary key (id)
    );

    create table reservations (
        montant_total float(53) not null,
        nombre_places integer not null,
        date_reservation timestamp(6) not null,
        evenement_id bigint not null,
        id bigint generated by default as identity,
        utilisateur_id bigint not null,
        commentaire varchar(500),
        code_reservation varchar(255) not null unique,
        statut enum ('ANNULEE','CONFIRMEE','EN_ATTENTE') not null,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role enum ('ADMIN','CLIENT','ORGANIZER') not null,
        primary key (id)
    );

    alter table if exists events 
       add constraint FK5yk99wir13s55ueack8plvtyd 
       foreign key (organisateur_id) 
       references users;

    alter table if exists reservations 
       add constraint FK8jesmpbtkragkbvbrfleldwhr 
       foreign key (evenement_id) 
       references events;

    alter table if exists reservations 
       add constraint FKog5mieccgchsbj6f97w02uj53 
       foreign key (utilisateur_id) 
       references users;

    create table contact_messages (
        is_important boolean not null,
        is_read boolean not null,
        id bigint generated by default as identity,
        read_at timestamp(6),
        sent_at timestamp(6) not null,
        message varchar(2000) not null,
        email varchar(255) not null,
        name varchar(255) not null,
        subject varchar(255) not null,
        primary key (id)
    );

    create table events (
        capacite_max integer not null check (capacite_max>=1),
        prix_unitaire float(53) not null check (prix_unitaire>=0),
        date_creation timestamp(6) not null,
        date_debut timestamp(6) not null,
        date_fin timestamp(6),
        date_modification timestamp(6),
        id bigint generated by default as identity,
        organisateur_id bigint not null,
        titre varchar(100) not null,
        image_path varchar(500),
        description varchar(1000),
        lieu varchar(255) not null,
        ville varchar(255) not null,
        categorie enum ('AUTRE','CONCERT','CONFERENCE','SPORT','THEATRE') not null,
        statut enum ('ANNULE','BROUILLON','PUBLIE','TERMINE') not null,
        primary key (id)
    );

    create table reservations (
        montant_total float(53) not null,
        nombre_places integer not null,
        date_reservation timestamp(6) not null,
        evenement_id bigint not null,
        id bigint generated by default as identity,
        utilisateur_id bigint not null,
        commentaire varchar(500),
        code_reservation varchar(255) not null unique,
        statut enum ('ANNULEE','CONFIRMEE','EN_ATTENTE') not null,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role enum ('ADMIN','CLIENT','ORGANIZER') not null,
        primary key (id)
    );

    alter table if exists events 
       add constraint FK5yk99wir13s55ueack8plvtyd 
       foreign key (organisateur_id) 
       references users;

    alter table if exists reservations 
       add constraint FK8jesmpbtkragkbvbrfleldwhr 
       foreign key (evenement_id) 
       references events;

    alter table if exists reservations 
       add constraint FKog5mieccgchsbj6f97w02uj53 
       foreign key (utilisateur_id) 
       references users;
