-- ============================================
-- SCHÉMA DE LA BASE DE DONNÉES - EVENTIA
-- Système de Gestion de Réservations d'Événements
-- ============================================

-- Supprimer les tables existantes (pour un redémarrage propre)
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS contact_messages CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================
-- TABLE USERS
-- ============================================
CREATE TABLE users (
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('ADMIN', 'CLIENT', 'ORGANIZER') NOT NULL,
    PRIMARY KEY (id)
);

-- ============================================
-- TABLE EVENTS
-- ============================================
CREATE TABLE events (
    capacite_max INTEGER NOT NULL CHECK (capacite_max >= 1),
    prix_unitaire FLOAT(53) NOT NULL CHECK (prix_unitaire >= 0),
    date_creation TIMESTAMP(6) NOT NULL,
    date_debut TIMESTAMP(6) NOT NULL,
    date_fin TIMESTAMP(6),
    date_modification TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    organisateur_id BIGINT NOT NULL,
    titre VARCHAR(100) NOT NULL,
    image_path VARCHAR(500),
    description VARCHAR(1000),
    lieu VARCHAR(255) NOT NULL,
    ville VARCHAR(255) NOT NULL,
    categorie ENUM('AUTRE', 'CONCERT', 'CONFERENCE', 'SPORT', 'THEATRE') NOT NULL,
    statut ENUM('ANNULE', 'BROUILLON', 'PUBLIE', 'TERMINE') NOT NULL,
    PRIMARY KEY (id)
);

-- ============================================
-- TABLE RESERVATIONS
-- ============================================
CREATE TABLE reservations (
    montant_total FLOAT(53) NOT NULL,
    nombre_places INTEGER NOT NULL,
    date_reservation TIMESTAMP(6) NOT NULL,
    evenement_id BIGINT NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    utilisateur_id BIGINT NOT NULL,
    commentaire VARCHAR(500),
    code_reservation VARCHAR(255) NOT NULL UNIQUE,
    statut ENUM('ANNULEE', 'CONFIRMEE', 'EN_ATTENTE') NOT NULL,
    PRIMARY KEY (id)
);

-- ============================================
-- TABLE CONTACT_MESSAGES
-- ============================================
CREATE TABLE contact_messages (
    is_important BOOLEAN NOT NULL,
    is_read BOOLEAN NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    read_at TIMESTAMP(6),
    sent_at TIMESTAMP(6) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- ============================================
-- CLÉS ÉTRANGÈRES
-- ============================================
ALTER TABLE IF EXISTS events 
    ADD CONSTRAINT FK5yk99wir13s55ueack8plvtyd 
    FOREIGN KEY (organisateur_id) 
    REFERENCES users(id);

ALTER TABLE IF EXISTS reservations 
    ADD CONSTRAINT FK8jesmpbtkragkbvbrfleldwhr 
    FOREIGN KEY (evenement_id) 
    REFERENCES events(id);

ALTER TABLE IF EXISTS reservations 
    ADD CONSTRAINT FKog5mieccgchsbj6f97w02uj53 
    FOREIGN KEY (utilisateur_id) 
    REFERENCES users(id);